name: Frontend Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build --prod
      
    - name: Debug - List all files
      run: |
        echo "Root directory:"
        ls -la
        echo "Dist directory:"
        ls -la dist/ || echo "No dist folder found"
        find . -name "index.html" -type f
        
    - name: Create netlify.toml
      run: |
        cat > netlify.toml << EOF
        [build]
          publish = "dist/expednow"
          command = "npm run build --prod"
        
        [[redirects]]
          from = "/*"
          to = "/index.html"
          status = 200
        EOF
        
    - name: Install Netlify CLI
      run: npm install -g netlify-cli
      
    - name: Deploy to Netlify
      run: |
        if [ -d "dist/expednow" ]; then
          netlify deploy --prod --dir=dist/expednow
        elif [ -d "dist" ]; then
          netlify deploy --prod --dir=dist
        else
          echo "No valid dist directory found"
          exit 1
        fi
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
    - name: Deployment Status
      run: echo "🚀 Frontend deployed successfully!"