name: Frontend Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --configuration production
      
    - name: Debug build output
      run: |
        echo "Build completed. Checking output..."
        ls -la dist/
        find dist -name "index.html"
        
    - name: Install Netlify CLI
      run: npm install netlify-cli -g
      
    - name: Deploy to Netlify
      run: netlify deploy --prod --dir=dist/expednow
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}